server:
  port: 81


spring:
  mvc:
#    static-path-pattern: /res/**
    hiddenmethod:
      filter:
        enabled: true

#這個會導致index失效，favicon失效
#  web:
#    resources:
#      static-locations: /hey/

